config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }


  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: :commentable, shallow: true do
    resources :answers, concerns: :commentable, only: %i[create destroy update], shallow: true do
      post :like
      post :dislike
    end
    post :best_answer
    post :like
    post :dislike
  end

  root to: 'questions#index'
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, :body, :user_id, presence: true

  has_many :answers
  has_many :attachments, as: :attachable
  has_many :votes, as: :votable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  belongs_to :user, foreign_key: 'user_id'
  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, only: %i[show edit update destroy]
  before_action :build_answer, only: :show
  after_action :publish_question, only: :create

  respond_to :html

  authorize_resource

  include Voted

  def index
    respond_with(@questions = Question.all)
  end

  def show
    answers = @question.answers
    best = answers.select { |answer| answer.id == @question.best_answer }
    @answers = best + (answers - best)
    response.headers['Cache-Control'] = 'no-cache, no-store'
    @comment = @question.comments.build
    respond_with @question
  end

  def new
    respond_with(@question = Question.new)
  end

  def edit; end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    @question.update(question_params)
    respond_with @question
  end

  def destroy
    flash[:notice] = 'Your question has been deleted.' if @question.destroy
    respond_with(@question.destroy)
  end

  def best_answer
    @question = Question.find(params[:question_id])
    @question.update(best_answer: params[:answer_id])
    @question.reload
    redirect_to question_path(@question)
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def publish_question
    PrivatePub.publish_to '/questions/new', question: @question.to_json if @question.valid?
  end

  def build_answer
    @answer = @question.answers.build
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: %i[id file _destroy])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answers.html.slim
ul
  - @answers.each do |answer|
    - if answer.persisted?
      li
        i
          - if answer.user
            = answer.user.email + ': '
          - else
            = 'No user: '

        = answer.body
        - answer.attachments.each do |a|
          p= link_to a.file.identifier, a.file.url
          - if current_user == answer.user
        p
          - if current_user && current_user != answer.user
            = link_to 'Like this answer', answer_like_path(@question.id, answer_id: answer.id), method: :post, remote: true, class: 'answer_like', id: "like-btn-answer-#{answer.id}"
            = link_to 'Dislike this answer', answer_dislike_path(@question.id, answer_id: answer.id), method: :post, remote: true, class: 'answer_dislike', id: "dislike-btn-answer-#{answer.id}"
          = render 'answers/answer_digits', answer: answer

        - if answer.id == @question.best_answer
          = image_tag Emoji.image_url_for_name('glowing_star')
          = 'This is the best answer.'

        - else
          - if current_user == @question.user
            = button_to 'Make this answer the best', question_best_answer_path(@question.id, answer_id: answer.id)

        .comments
          p
            b Comments: &nbsp
            div class="#{answer.class.to_s.underscore}_comments"
              = render 'comments/list', poly_model: answer
          p
            - if current_user == answer.user
              = link_to 'Edit', '', class: 'edit-answer-link', id: "edit-btn-answer-#{answer.id}", data: { answer_id: answer.id }
              = form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}"} do |form|
                .field
                  = form.label :body, "Answer"
                  = form.text_area :body
                = form.fields_for :attachments do |a|
                  = render 'questions/attachment_fields', f: a
                .links
                  = link_to_add_association 'add file to answer', form, :attachments
                = form.submit 'Save answer'
              p= link_to 'Delete answer', answer_path(answer.id, question_id: @question.id), method: :delete, data: { confirm: 'Are you sure?' }, remote: true

    = subscribe_to "/answer/#{answer.id}/comments"
javascript:
    $('.edit-answer-link').click(function (e) {
        answer_id = $(this).data('answerId');
        $('form#edit-answer-' + answer_id).show();
        e.preventDefault();
    });

app/views/questions/_attachment_fields.html.slim
.nested-fields
  .field
    = f.label :file
    b
    = f.file_field :file
  = link_to_remove_association "remove file", f
  = ' '

app/views/questions/_form.html.slim
= form_for @question, remote: true do |form|
  .field
    = form.label :title
    b
    = form.text_field :title
  .field
    = form.label :body
    b
    = form.text_area :body
  h Attachments:
  p
    = form.fields_for :attachments, @question.attachments.build do |a|
      = render 'attachment_fields', f: a
    .links
      = link_to_add_association 'add file', form, :attachments
  b= form.submit 'Save'

app/views/questions/_question_digits.html.slim
div#question_digits
  p
    b = image_tag Emoji.image_url_for_name('thumbs_up_sign')
    - questions_likes = question.votes.select(&:like).size
    = questions_likes
    b = image_tag Emoji.image_url_for_name('unamused')
    - questions_dislikes = question.votes.select { |v| v.dislike }.size
    = questions_dislikes
    b
      - rating = questions_likes - questions_dislikes
      - if rating >= 0
        = image_tag Emoji.image_url_for_name('up3')
      - else
        = image_tag Emoji.image_url_for_name('down')
      = rating

app/views/questions/_table.html.slim
table border=1
  thead
    th Number
    th Question title
    th Question body
  tbody
    .questions_list
      - @questions.each do |question|
        tr
          td= question.id
          td= link_to question.title, question
          td= question.body

app/views/questions/create.js.erb
<% publish_to "/questions/" do %>
  $('.questions').html('<%= j render 'table' %>');
<% end %>

app/views/questions/dislike.js.erb
$('#dislike').on("click", function() {
       $('#question_digits').replaceWith('<%= j render "question_digits", question: @question %>')
})

app/views/questions/edit.html.slim
h1 Editing question

= render 'form'

/= link_to 'Home'

app/views/questions/index.html.slim
h1 Questions

p
  b Current user: &nbsp
  - if current_user
    = current_user.email + ': '
  - else
    = 'Please, log in to ask or answer the questions'

= render 'questions/table'
- if can?(:create, Question)
  p= link_to 'Ask question', new_question_path

= subscribe_to "/questions/new"

app/views/questions/like.js.erb
$('#like').on("click", function() {
       $('#question_digits').html('<%= j render "question_digits", question: @question %>')
})

app/views/questions/new.html.slim
/ = form_for @question do |f|
/   = f.label :title
/   = f.text_field :title
/   = f.label :body
/   = f.text_area :body
/
/   = f.submit 'Create'
h1 New question
= render 'form'

app/views/questions/show.html.slim
.question
  h1 Question
  i
    - if current_user == @question.user
      = link_to 'Edit question', edit_question_path(@question.id)
      = ' '
      = link_to 'Delete', question_path(@question.id), method: :delete, data: {confirm: 'Are you sure?'}
  p
    b Current user: &nbsp
    - if current_user
      = current_user.email
    - else
      = 'no user'
  p
    b Question author: &nbsp
    - if @question.user
      = @question.user.email
    - else
      = 'no user'
  p
    b Title: &nbsp
    = @question.title
  p
    b Body: &nbsp
    i = @question.body
  p
    b Attachments: &nbsp
    p
      - @question.attachments.each do |a|
        li= link_to a.file.identifier, a.file.url
  p
    - if current_user && current_user != @question.user
      = link_to 'Like it ', question_like_path(@question.id), method: :post, remote: true, id: 'like', 'data-no-turbolink' => true
      = link_to 'Dislike it ', question_dislike_path(@question.id), method: :post, remote: true, id: 'dislike', data: { turbolinks: 'false' }
  div#question_digits
    = render 'question_digits', question: @question
  p
    b Comments: &nbsp
    .comments
      div class="#{@question.class.to_s.underscore}_comments"
        = render 'comments/list', poly_model: @question

  p
    b Answers:
    .answers data={question_id: "#{@question.id}" }
      = render 'questions/answers'

  p
    - if current_user
      = form_for [@question, Answer.new], remote: true do |form|
        .field
          = form.label :body, 'Your answer'
          .answer-errors
          = form.text_area :body
        = form.fields_for :attachments, @answer.attachments.build do |a|
          = render 'attachment_fields', f: a
        .links
          = link_to_add_association 'add file', form, :attachments
        = form.submit 'Save answer'

  = subscribe_to "/question/#{@question.id}/answers"
  = subscribe_to "/question/#{@question.id}/comments"