config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }


  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: :commentable, shallow: true do
    resources :answers, concerns: :commentable, only: %i[create destroy update], shallow: true do
      post :like
      post :dislike
    end
    post :best_answer
    post :like
    post :dislike
  end

  root to: 'questions#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  belongs_to :commentable, polymorphic: true

  validates :user_id, :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]
  before_action :current_user, only: [:destroy]
  before_action :load_comment, only: %i[update destroy]
  before_action :load_poly_model, only: %i[create update destroy]

  respond_to :js

  def create
    respond_with(@comment = @polymorphic_model.comments.create(comment_params.merge(user_id: current_user.id)))
  end

  def update
    @comment.update(comment_params)
    @question = @comment.question
    @comments = @polymorphic_model.answers
    respond_with @comment
  end

  def destroy
    respond_with(@comment = @polymorphic_model.comments.find_by(user_id: current_user.id, id: params[:id]).destroy)
  end

  private

  def load_poly_model
    @polymorphic_model = if params[:answer_id]
                           Answer.find(params[:answer_id])
                         else
                           Question.find(params[:question_id])
    end
  end

  def load_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/views/comments/_comment.html.slim
/ p= comment.body

app/views/comments/_list.html.slim
= render poly_model.comments
ul
  - poly_model.comments.each do |comment|
    - if comment.persisted?
      li
        i
          - if comment.user
            = comment.user.email + ': '
          - else
            = 'No user: '

        = comment.body
      p
        - if current_user == comment.user
          p= link_to 'Delete', comment_path(comment.id, "#{poly_model.class.to_s.downcase}_id" => poly_model.id), method: :delete, data: {confirm: 'Are you sure?'}, remote: true

  p
    - if current_user
      - if poly_model.is_a? Question
        = form_for [poly_model, poly_model.comments.new], remote: true do |form|
          .field
            = form.label :body, 'Question comment'
            = form.text_area :body
          = form.submit 'Save question comment'
      - else
        = form_for Comment.new, url: answer_comments_path(question_id: poly_model.question.id, answer_id: poly_model.id), method: :post, remote: true do |form|
          .field
            = form.label :body, 'Answer comment'
            = form.text_area :body
          = form.submit 'Save answer comment'

app/views/comments/create.js.erb
<% if @comment.errors.present? %>
  <% @comment.errors.full_messages.each do |message| %>
    $('.comment_errors').html('<%= j message %>');
  <% end %>
<% else %>
  <% pmodel = @polymorphic_model.class.to_s.underscore %>
  <% publish_to "/#{pmodel}/#{@polymorphic_model.id}/comments" do %>
    $('.<%= pmodel %>_comments').html('<%= j render 'comments/list', poly_model: @polymorphic_model %>');
  <% end %>
  $('.new_comment #comment_body').val('');
  console.log('<%= "/#{pmodel}/#{@polymorphic_model.id}/comments" %>');
<% end %>

app/views/comments/destroy.js.erb
<% pmodel = @polymorphic_model.class.to_s.underscore %>
<% publish_to "/#{pmodel}/#{@polymorphic_model.id}/comments" do %>
  $('.<%= pmodel %>_comments').html('<%= j render 'comments/list', poly_model: @polymorphic_model %>');
<% end %>